version: '3'
services:
  web:
    image: express-react:demo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "express-react"
    ports:
      - "5000:5000"
      - "3000:3000"
    restart: always
    links:
      - db
  db:
    image: mongo:express-react
    build:
      context: ./server/db
      dockerfile: Dockerfile
    container_name: "mongo-express"
    ports:
      - "27017:27017"
    restart: always
