version: '3'
services:

  mongo:
    image: mongo:express-react
    build:
      context: ./server/db
      dockerfile: Dockerfile
    container_name: "mongo-express"
    volumes:
      - "mongo-project:/data/db"
    ports:
      - "27017:27017"
    restart: always

  web:
    image: express-react:demo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "express-react"
    ports:
      - "5000:5000"
      - "3000:3000"
    restart: always
    links:
      - mongo
    depends_on:
      - mongo

volumes:
        mongo-project:
